Chapter 2 Regression and model validation
=======

*Describe the work you have done this week and summarize your learning.*

- data wrangling exercise 
- linear regression model analysis (simple or Multiple linear regression) 


**1 loading data and check data**
```{r}
students2014 <- read.table("http://s3.amazonaws.com/assets.datacamp.com/production/course_2218/datasets/learning2014.txt", header = T, sep = ",")
str(students2014)
head(students2014)
summary(students2014)
plot(students2014[2:7], )

```


**2 over view correlation **
```{r}
library("PerformanceAnalytics")
chart.Correlation(students2014[2:7],histogram=TRUE, pch=19)
```

**3 regression model for "three variables as explanatory variables"**
```{r}
model1 <- lm(points ~ attitude + stra + surf, data = students2014)
summary(model1)
### stra and surf are not significant!

### remove the un-significant variables and model again
model2 <- lm(points ~ attitude, data = students2014)
summary(model2)
### the intercept of the model2 is 11.6372, and slop is 3.5255, Multiple R-squared is 0.1906
```

**4 diagnostic plots**
```{r}
par(mfrow = c(2,2))
plot(model2)

```


